version: '3.8'

services:
  api:
    build: .
    ports:
      - 8000:8000
    depends_on:
      - database
    volumes:
      - .:/app
    command: >
      bash -c "alembic upgrade head && 
               uvicorn app.main:app --host 0.0.0.0 --port 8000"

  database:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_pass
      POSTGRES_DB: test_project
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - 5432:5432
